version: '2.2'

services:
  mariadb:
    image: mariadb:10.4.12
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=redmine_production
    - MYSQL_USER=redmine
    - MYSQL_PASSWORD=password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./redmine_data/mysql:/var/lib/mysql

  redmine:
    build: ./
    image: sameersbn/redmine:4.1.1-8
    depends_on:
    - mariadb
    environment:
    - TZ=Asia/Seoul

    - DB_ADAPTER=mysql2
    - DB_HOST=mariadb
    - DB_PORT=3306
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production

    # - REDMINE_PORT=10083
    # - REDMINE_HTTPS=false
    # - REDMINE_RELATIVE_URL_ROOT=
    # - REDMINE_SECRET_TOKEN=

    # - REDMINE_SUDO_MODE_ENABLED=false
    # - REDMINE_SUDO_MODE_TIMEOUT=15

    # - REDMINE_CONCURRENT_UPLOADS=2

     - REDMINE_BACKUP_SCHEDULE=daily
    #- REDMINE_BACKUP_EXPIRY=
     - REDMINE_BACKUP_TIME=04:00

    # - SMTP_ENABLED=false
    # - SMTP_METHOD=smtp
    # - SMTP_DOMAIN=www.example.com
    # - SMTP_HOST=smtp.gmail.com
    # - SMTP_PORT=587
    # - SMTP_USER=mailer@example.com
    # - SMTP_PASS=password
    # - SMTP_STARTTLS=true
    # - SMTP_AUTHENTICATION=:login

    # - IMAP_ENABLED=false
    # - IMAP_HOST=imap.gmail.com
    # - IMAP_PORT=993
    # - IMAP_USER=mailer@example.com
    # - IMAP_PASS=password
    # - IMAP_SSL=true
    # - IMAP_INTERVAL=30

    ports:
    - "80:80"

    volumes:
    - ./redmine_data:/home/redmine/data
    - ./redmine_data/logs:/var/log/redmine
    - ./redmine_data/vanillaBrain-project:/home/redmine/vanillaBrain-project
